name: Colcon Build, Test, Coverage and Autoformat

on:
  pull_request:
    branches:
      - dev
      - pre-release
      - release

  workflow_dispatch:

jobs:
  Autoformat:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Autoformat and Test
      uses: THI-Drone/workflow/.github/workflows/workflow.yml@main